[build]
publish = "dist"
command = "npm run build"
CI = "false"

[build.environment]
NODE_VERSION = "20"

[context.deploy-preview]
command = "npm run build"
CI = "false"

[context.branch-deploy]
command = "npm run build"
CI = "false"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
